import numpy as np

def _get_kilosort_spike_counts(activity: np.ndarray) -> np.ndarray: ...
def _get_occu_time(variable: np.ndarray, dtime: np.ndarray, nbins: int) -> np.ndarray: ...
def calc_neural_trajectory(spikes: np.ndarray, t_window: float, step_size: float) -> np.ndarray: ...
